kind: ConfigMap
apiVersion: v1
metadata:
  name: binder-config
data:
  binder.use-registry: {{ .Values.registry.enabled | quote }}
  {{ if .Values.registry.enabled -}}
  binder.push-secret: binder-secret
  binder.registry.host: {{ .Values.registry.host | quote }}
  {{ end -}}
  {{ if .Values.googleAnalyticsCode -}}
  binder.google-analytics-code: {{ .Values.googleAnalyticsCode | quote }}
  {{- end }}
  {{ if .Values.googleAnalyticsDomain -}}
  binder.google-analytics-domain: {{ .Values.googleAnalyticsDomain | quote }}
  {{- end }}
  binder.cors: {{ toJson .Values.cors | quote }}
  binder.registry.prefix: {{ .Values.registry.prefix | quote }}
  binder.repo2docker-image: {{ .Values.repo2dockerImage | quote }}
  binder.hub-url: {{ .Values.hub.url | quote }}
  binder.base-url: {{ .Values.baseUrl | quote }}
  {{ if .Values.enableFederationPortal -}}
  binder.enable-federation-portal: {{ .Values.enableFederationPortal }}
  {{- end }}
  {{ if .Values.federationSiteAddress -}}
  binder.federation-site-address: {{.Values.federationSiteAddress | quote }}
  {{- end }}
  {{ if .Values.enableFederationSitesCookie -}}
  binder.enable-federation-sites-cookie: {{ .Values.enableFederationSitesCookie }}
  {{- end }}
  {{ if .Values.defaultBinders -}}
  binder.default-binders-list:
{{toYaml .Values.defaultBinders | indent 4 }}
  {{- end}}

  dind.enabled: {{ .Values.dind.enabled | quote }}
  {{ if .Values.dind.enabled }}
  dind.host-socket-dir: {{ .Values.dind.hostSocketDir | quote }}
  {{ end }}

  {{ if .Values.extraConfig }}
  {{ range $key, $value := .Values.extraConfig -}}
  extra-config.{{ $key }}.py: |
{{ $value | indent 4 }}
  {{- end }}
  {{- end }}
