kind: ConfigMap
apiVersion: v1
metadata:
  name: binder-config
data:
  binder.use-registry: {{ .Values.registry.enabled | quote }}
  {{ if .Values.registry.enabled -}}
  binder.push-secret: binder-secret
  binder.registry.host: {{ .Values.registry.host | quote }}
  {{ end -}}
  {{ if .Values.googleAnalyticsCode -}}
  binder.google-analytics-code: {{ .Values.googleAnalyticsCode | quote }}
  {{- end }}
  {{ if .Values.googleAnalyticsDomain -}}
  binder.google-analytics-domain: {{ .Values.googleAnalyticsDomain | quote }}
  {{- end }}
  binder.cors: {{ toJson .Values.cors | quote }}
  binder.registry.prefix: {{ .Values.registry.prefix | quote }}
  binder.repo2docker-image: {{ .Values.repo2dockerImage | quote }}
  binder.hub-url: {{ .Values.hub.url | quote }}
  binder.base_url: {{ .Values.baseUrl | quote }}
  {{ if .Value.use_as_federation_portal -}}
  binder.use_as_federation_portal: {{ .Value.use_as_federation_portal }}
  {{- end }}
  binder.cannonical_address: {{.Values.cannonical_address | quote }}
  {{ if .Value.list_cookie_set_binders -}}
  binder.list_cookie_set_binders: {{ .Values.list_cookie_set_binders }}
  {{- end }}
  {{ if .Value.default_binders_list-}}
  binder.default_binders_list:
  {{ range $value := .Values.default_binders_list -}}
{{'-'+$value | indent 4 }}
  {{-end}}
  {{-end}}

  dind.enabled: {{ .Values.dind.enabled | quote }}
  {{ if .Values.dind.enabled }}
  dind.host-socket-dir: {{ .Values.dind.hostSocketDir | quote }}
  {{ end }}

  {{ if .Values.extraConfig }}
  {{ range $key, $value := .Values.extraConfig -}}
  extra-config.{{ $key }}.py: |
{{ $value | indent 4 }}
  {{- end }}
  {{- end }}
