kind: ConfigMap
apiVersion: v1
metadata:
  name: binder-config
data:
  binder.use-registry: {{ .Values.registry.enabled | quote }}
  {{ if .Values.registry.enabled -}}
  binder.push-secret: binder-secret
  binder.registry.host: {{ .Values.registry.host | quote }}
  {{ end -}}
  {{ if .Values.googleAnalyticsCode -}}
  binder.google-analytics-code: {{ .Values.googleAnalyticsCode | quote }}
  {{- end }}
  {{ if .Values.googleAnalyticsDomain -}}
  binder.google-analytics-domain: {{ .Values.googleAnalyticsDomain | quote }}
  {{- end }}
  binder.cors: {{ toJson .Values.cors | quote }}
  binder.registry.prefix: {{ .Values.registry.prefix | quote }}
  binder.repo2docker-image: {{ .Values.repo2dockerImage | quote }}
  binder.hub-url: {{ .Values.hub.url | quote }}
  binder.base-url: {{ .Values.baseUrl | quote }}
  {{ if .Values.useAsFederationPortal -}}
  binder.use-as-federation-portal: {{ .Values.useAsFederationPortal }}
  {{- end }}
  {{ if .Values.cannonicalAddress -}}
  binder.cannonical-address: {{.Values.cannonicalAddress | quote }}
  {{- end }}
  {{ if .Values.listCookieSetBinders -}}
  binder.list-cookie-set-binders: {{ .Values.listCookieSetBinders }}
  {{- end }}
  {{ if .Values.defaultBindersList -}}
  binder.default-binders-list:
{{toYaml .Values.defaultBindersList | indent 4 }}
  {{- end}}

  dind.enabled: {{ .Values.dind.enabled | quote }}
  {{ if .Values.dind.enabled }}
  dind.host-socket-dir: {{ .Values.dind.hostSocketDir | quote }}
  {{ end }}

  {{ if .Values.extraConfig }}
  {{ range $key, $value := .Values.extraConfig -}}
  extra-config.{{ $key }}.py: |
{{ $value | indent 4 }}
  {{- end }}
  {{- end }}
